packages:
  - packages/components/*
  - packages/storybook

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - husky
  - nx

linkWorkspacePackages: "deep"
preferWorkspacePackages: true
hoistWorkspacePackages: true
publicHoistPattern:
  - "*eslint*"
