export const MENU_WIDTH_OFFSET = 17;
export const INPUT_EXPAND_ANIMATION_DURATION = 100;
export const SCROLLBAR_HEIGHT_OFFSET = 28;
export const LIST_HEADER_HEIGHT = 42;

export const LABEL_LEFT_OFFSET = 7;
export const ANIMATION_DURATION = INPUT_EXPAND_ANIMATION_DURATION / 1000;
export const MAX_FILTER_WIDTH = 120;
