export const COLUMNS = [
  {
    title: 'Name',
    dataIndex: 'name',
    fixed: 'left',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'name',
  },
  {
    title: 'City',
    dataIndex: 'city',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'city',
  },
  {
    title: 'System',
    dataIndex: 'system',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'system',
  },
  {
    title: 'Format',
    dataIndex: 'format',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'format',
  },
  {
    title: 'Age',
    dataIndex: 'age',
    fixed: 'right',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'age',
  },
];
