import { InfoFillS, VarTypeNumberM, VarTypeStringM } from '@synerise/ds-icon';
import React from 'react';

export const COLUMNS = [
  {
    title: 'Name',
    dataIndex: 'name',
    width: 254,
    fixed: 'left',
    key: 'name',
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.name.localeCompare(b.name),
      multiple: 1,
    },
    sortRender: 'string',
    defaultSortOrder: 'ascend',
  },
  {
    title: 'City',
    dataIndex: 'city',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'city',
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.city.localeCompare(b.city),
      multiple: 2,
    },
    sortRender: 'string',
  },
  {
    title: 'System',
    dataIndex: 'system',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'system',
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.system.localeCompare(b.system),
      multiple: 3,
    },
    sortRender: 'string',
  },
  {
    title: 'Format',
    dataIndex: 'format',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'format',
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.system.localeCompare(b.system),
      multiple: 4,
    },
    sortRender: 'string',
  },
  {
    title: 'Age',
    dataIndex: 'age',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    fixed: 'right',
    key: 'age',
    icon: { component: <VarTypeNumberM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.age - b.age,
      multiple: 5,
    },
  },
];
