import React from 'react';
import { action } from 'storybook/actions';

import Icon, {
  InfoFillS,
  OptionHorizontalM,
  SettingsM,
  VarTypeBooleanM,
  VarTypeDateM,
  VarTypeListM,
  VarTypeNumberM,
  VarTypeStringM,
} from '@synerise/ds-icon';
import { DSColumnType, TableCell } from '@synerise/ds-table';
import Button from '@synerise/ds-button';
import { UserAvatar } from '@synerise/ds-avatar';
import { focusWithArrowKeys } from '@synerise/ds-utils';
import Menu from '@synerise/ds-menu';
import Dropdown from '@synerise/ds-dropdown';

import { RELATIONS } from '../AllCellTypes/AllCellTypes.data';
import { AdditionalColumnData } from '../Table.types';
import { AVATAR_IMAGE } from '../../../constants';

const menuData = [
  { text: 'Preview' },
  { text: 'Edit' },
  { text: 'Duplicate' },
  { type: 'divider' },
  { text: 'Delete', type: 'danger' },
];

export const DATA_SOURCE = [
  {
    key: 1,
    name: 'Dr. Ralph Abbott',
    city: 'Warsaw',
    age: 55,
    system: 'OSX',
    format: 'JPG',
    lang: 'en',
    firstName: 'Martyna',
    lastName: 'Testovi',
    phone: '678990320',
    color: 'purple',
    last_activity: '2025-02-01T15:32:32+01:00',
    active: false,
    country: 'ru',
    address: '621 Judy Plains',
    status: 'blocked',
    enabled: false,
    editable: 'Lionel Larson',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 2,
    name: 'Bob Runte-Altenwerth',
    city: 'Berlin',
    age: 54,
    system: 'Windows',
    format: 'JPG',
    lang: 'pl',
    firstName: 'Michelle',
    lastName: 'Testinson',
    phone: '588991567',
    color: 'yellow',
    last_activity: '2024-12-08T05:12:15+01:00',
    active: true,
    country: 'it',
    address: '934 Konopelski Vista',
    status: 'active',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 3,
    name: 'Harry Grady',
    city: 'Warsaw',
    age: 23,
    system: 'Windows',
    format: 'JPG',
    lang: 'es',
    firstName: 'Anita',
    lastName: 'Testovi',
    phone: '678990320',
    color: 'purple',
    last_activity: '2024-12-27T20:57:27+01:00',
    active: true,
    country: 'de',
    address: '45144 Lydia Prairie',
    status: 'active',
    enabled: false,
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 4,
    name: 'Dominick Kulas',
    city: 'Warsaw',
    age: 35,
    system: 'Linux',
    format: 'png',
    lang: 'pl',
    firstName: 'Stefan',
    lastName: 'Testovi',
    phone: '631001372',
    color: 'green',
    last_activity: '2024-12-04T10:51:05+01:00',
    active: true,
    country: 'ru',
    address: '97755 Muller Island',
    status: 'blocked',
    enabled: false,
    editable: 'Jerald Funk',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 5,
    name: 'Matt Rodriguez',
    city: 'London',
    age: 49,
    system: 'Linux',
    format: 'png',
    lang: 'pl',
    firstName: 'Wojtek',
    lastName: 'Testovich',
    phone: '678990320',
    color: 'violet',
    last_activity: '2024-12-21T23:54:03+01:00',
    active: true,
    country: 'pl',
    address: '41980 Church Road',
    status: 'inactive',
    enabled: false,
    editable: 'Troy Beahan',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 6,
    name: 'Sylvia Green',
    city: 'Paris',
    age: 37,
    system: 'OSX',
    format: 'JPG',
    lang: 'es',
    firstName: 'Wiktoria',
    lastName: 'Doe',
    phone: '571345127',
    color: 'blue',
    last_activity: '2025-01-05T20:13:57+01:00',
    active: true,
    country: 'de',
    address: '575 Kunze Estates',
    status: 'blocked',
    enabled: true,
    editable: 'Miriam Bradtke',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 7,
    name: 'Ida Quitzon',
    city: 'New York',
    age: 45,
    system: 'Linux',
    format: 'Zip',
    lang: 'es',
    firstName: 'Marek',
    lastName: 'Testovich',
    phone: '588991567',
    color: 'purple',
    last_activity: '2024-11-15T21:46:20+01:00',
    active: true,
    country: 'es',
    address: '38209 Hudson Flats',
    status: 'inactive',
    enabled: true,
    editable: 'John Muller',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 8,
    name: 'Ellis Cummerata',
    city: 'Denver',
    age: 26,
    system: 'Windows',
    format: 'png',
    lang: 'es',
    firstName: 'Stefan',
    lastName: 'Kowalczyk',
    phone: '666245912',
    color: 'yellow',
    last_activity: '2025-01-04T11:14:29+01:00',
    active: true,
    country: 'it',
    address: '6520 Prince Coves',
    status: 'active',
    enabled: false,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 9,
    name: 'Doreen Jakubowski',
    city: 'London',
    age: 20,
    system: 'OSX',
    format: 'Zip',
    lang: 'es',
    firstName: 'Marek',
    lastName: 'Testovich',
    phone: '666245912',
    color: 'green',
    last_activity: '2024-11-27T13:24:14+01:00',
    active: true,
    country: 'es',
    address: '9609 Pattie Ford',
    status: 'blocked',
    enabled: false,
    editable: 'Naomi Mills',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 10,
    name: 'Sonya Bayer',
    city: 'Warsaw',
    age: 27,
    system: 'Linux',
    format: 'JPG',
    lang: 'es',
    firstName: 'Wojtek',
    lastName: 'Testinson',
    phone: '654666871',
    color: 'yellow',
    last_activity: '2024-10-27T06:55:53+01:00',
    active: true,
    country: 'pl',
    address: '776 Norma Ferry',
    status: 'active',
    enabled: true,
    editable: 'Angel Donnelly',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 11,
    name: 'Jeff Rowe DDS',
    city: 'Warsaw',
    age: 54,
    system: 'OSX',
    format: 'Zip',
    lang: 'en',
    firstName: 'Anita',
    lastName: 'Testinson',
    phone: '678990320',
    color: 'red',
    last_activity: '2025-01-05T01:50:41+01:00',
    active: false,
    country: 'ru',
    address: '55145 Hertha Harbors',
    status: 'inactive',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 12,
    name: 'Gina Graham',
    city: 'Paris',
    age: 14,
    system: 'OSX',
    format: 'JPG',
    lang: 'es',
    firstName: 'Michelle',
    lastName: 'Kowalczyk',
    phone: '666245912',
    color: 'yellow',
    last_activity: '2025-01-09T16:10:53+01:00',
    active: false,
    country: 'pl',
    address: '1305 Bernardo Flats',
    status: 'inactive',
    enabled: true,
    editable: 'Betsy Hudson',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 13,
    name: 'Simon Bartell',
    city: 'London',
    age: 27,
    system: 'OSX',
    format: 'Zip',
    lang: 'pl',
    firstName: 'Marek',
    lastName: 'Kowalczyk',
    phone: '588991567',
    color: 'red',
    last_activity: '2024-12-09T10:57:57+01:00',
    active: true,
    country: 'es',
    address: '852 Kevin Brooks',
    status: 'blocked',
    enabled: false,
    editable: 'Philip Williamson DVM',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 14,
    name: 'Tony Trantow',
    city: 'New York',
    age: 48,
    system: 'OSX',
    format: 'png',
    lang: 'en',
    firstName: 'Wojtek',
    lastName: 'Doe',
    phone: '631001372',
    color: 'purple',
    last_activity: '2025-02-01T05:40:25+01:00',
    active: false,
    country: 'us',
    address: '36937 Neva Orchard',
    status: 'active',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 15,
    name: 'Brenda Koelpin',
    city: 'Berlin',
    age: 13,
    system: 'Linux',
    format: 'png',
    lang: 'en',
    firstName: 'Michelle',
    lastName: 'Doe',
    phone: '678990320',
    color: 'cyan',
    last_activity: '2024-11-15T08:33:37+01:00',
    active: false,
    country: 'pl',
    address: '32531 Dickinson Drives',
    status: 'blocked',
    enabled: false,
    editable: 'Edward Parker',
    checked: true,
    relations: RELATIONS,
    unavailable: true,
    disabled: true,
  },
  {
    key: 16,
    name: 'Miguel Greenholt',
    city: 'Warsaw',
    age: 18,
    system: 'Linux',
    format: 'png',
    lang: 'es',
    firstName: 'Stefan',
    lastName: 'Kowalczyk',
    phone: '654666871',
    color: 'green',
    last_activity: '2024-11-24T03:54:01+01:00',
    active: false,
    country: 'us',
    address: "7704 O'Kon Canyon",
    status: 'active',
    enabled: false,
    checked: true,
    relations: RELATIONS,
    unavailable: true,
    disabled: false,
  },
  {
    key: 17,
    name: 'Carlos Murphy-Kiehn',
    city: 'Denver',
    age: 13,
    system: 'OSX',
    format: 'png',
    lang: 'pl',
    firstName: 'Marek',
    lastName: 'Kowalczyk',
    phone: '654666871',
    color: 'violet',
    last_activity: '2024-11-03T08:23:12+01:00',
    active: true,
    country: 'de',
    address: '12093 Turcotte Underpass',
    status: 'inactive',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: true,
    disabled: true,
  },
  {
    key: 18,
    name: 'Dr. Glen Schneider',
    city: 'London',
    age: 40,
    system: 'Windows',
    format: 'JPG',
    lang: 'pl',
    firstName: 'Martyna',
    lastName: 'Testinson',
    phone: '678990320',
    color: 'purple',
    last_activity: '2024-12-02T14:29:19+01:00',
    active: true,
    country: 'pl',
    address: '6256 Cherry Tree Close',
    status: 'blocked',
    enabled: true,
    editable: 'Mr. Alex Raynor',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 19,
    name: 'Olga Erdman',
    city: 'Paris',
    age: 59,
    system: 'Linux',
    format: 'png',
    lang: 'es',
    firstName: 'Martyna',
    lastName: 'Testovi',
    phone: '571345127',
    color: 'blue',
    last_activity: '2024-10-16T05:26:23+02:00',
    active: true,
    country: 'es',
    address: '75323 Highfield Road',
    status: 'active',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 20,
    name: 'Emily Emmerich DVM',
    city: 'Berlin',
    age: 50,
    system: 'OSX',
    format: 'Zip',
    lang: 'es',
    firstName: 'Martyna',
    lastName: 'Kowalczyk',
    phone: '678990320',
    color: 'purple',
    last_activity: '2024-11-25T13:20:52+01:00',
    active: false,
    country: 'pl',
    address: '472 Kiana Isle',
    status: 'inactive',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 21,
    name: 'Sonia Hickle',
    city: 'Berlin',
    age: 27,
    system: 'Windows',
    format: 'png',
    lang: 'es',
    firstName: 'Wiktoria',
    lastName: 'Testovi',
    phone: '678990320',
    color: 'blue',
    last_activity: '2024-12-03T14:12:50+01:00',
    active: true,
    country: 'es',
    address: '3161 S Market Street',
    status: 'active',
    enabled: true,
    editable: 'Luis Nikolaus',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 22,
    name: 'Stephanie Thompson',
    city: 'Warsaw',
    age: 39,
    system: 'OSX',
    format: 'Zip',
    lang: 'pl',
    firstName: 'Wiktoria',
    lastName: 'Kowalczyk',
    phone: '654666871',
    color: 'cyan',
    last_activity: '2025-01-16T04:23:45+01:00',
    active: true,
    country: 'us',
    address: '686 Jerde Village',
    status: 'inactive',
    enabled: true,
    editable: 'Jo Sauer',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 23,
    name: 'Mr. Guillermo Bergstrom V',
    city: 'London',
    age: 11,
    system: 'OSX',
    format: 'JPG',
    lang: 'es',
    firstName: 'Marek',
    lastName: 'Testovich',
    phone: '666245912',
    color: 'violet',
    last_activity: '2024-10-30T19:46:00+01:00',
    active: true,
    country: 'ru',
    address: '47077 Walnut Street',
    status: 'inactive',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 24,
    name: 'Carol Conroy',
    city: 'Paris',
    age: 10,
    system: 'OSX',
    format: 'png',
    lang: 'en',
    firstName: 'Martyna',
    lastName: 'Testinson',
    phone: '571345127',
    color: 'orange',
    last_activity: '2024-10-31T03:49:37+01:00',
    active: false,
    country: 'it',
    address: '330 Susanna Walk',
    status: 'blocked',
    enabled: false,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 25,
    name: 'Jodi Jast',
    city: 'Warsaw',
    age: 34,
    system: 'OSX',
    format: 'Zip',
    lang: 'es',
    firstName: 'Wojtek',
    lastName: 'Kowalczyk',
    phone: '678990320',
    color: 'purple',
    last_activity: '2024-12-01T13:10:46+01:00',
    active: false,
    country: 'pl',
    address: '175 Randy Common',
    status: 'blocked',
    enabled: true,
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 26,
    name: 'Laverne Corwin V',
    city: 'Denver',
    age: 17,
    system: 'Linux',
    format: 'png',
    lang: 'en',
    firstName: 'Marek',
    lastName: 'Kowalczyk',
    phone: '678990320',
    color: 'blue',
    last_activity: '2024-12-29T04:46:13+01:00',
    active: false,
    country: 'pl',
    address: '97757 Orlo Bypass',
    status: 'blocked',
    enabled: true,
    editable: 'Lucy Langosh',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 27,
    name: 'Mack Mayert',
    city: 'Berlin',
    age: 18,
    system: 'Windows',
    format: 'png',
    lang: 'es',
    firstName: 'Anita',
    lastName: 'Testinson',
    phone: '588991567',
    color: 'cyan',
    last_activity: '2024-12-18T11:49:50+01:00',
    active: false,
    country: 'es',
    address: '85168 Grady Extensions',
    status: 'inactive',
    enabled: false,
    editable: 'Sam Schinner',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 28,
    name: 'Denise Block',
    city: 'Warsaw',
    age: 36,
    system: 'OSX',
    format: 'Zip',
    lang: 'en',
    firstName: 'Stefan',
    lastName: 'Doe',
    phone: '588991567',
    color: 'purple',
    last_activity: '2025-01-06T18:46:43+01:00',
    active: false,
    country: 'us',
    address: '82052 Tina Lake',
    status: 'inactive',
    enabled: true,
    editable: 'Cameron Waelchi',
    checked: true,
    relations: RELATIONS,
    unavailable: true,
    disabled: false,
  },
  {
    key: 29,
    name: 'Conrad Waelchi-Beer Sr.',
    city: 'Berlin',
    age: 54,
    system: 'OSX',
    format: 'Zip',
    lang: 'es',
    firstName: 'John',
    lastName: 'Testovich',
    phone: '588991567',
    color: 'red',
    last_activity: '2024-11-02T14:05:58+01:00',
    active: false,
    country: 'es',
    address: '43591 Albion Street',
    status: 'blocked',
    enabled: true,
    editable: 'Eugene Dooley',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 30,
    name: 'Amos Predovic',
    city: 'Paris',
    age: 33,
    system: 'OSX',
    format: 'png',
    lang: 'en',
    firstName: 'John',
    lastName: 'Testovi',
    phone: '631001372',
    color: 'orange',
    last_activity: '2024-11-13T17:09:35+01:00',
    active: false,
    country: 'es',
    address: '8969 The Grove',
    status: 'blocked',
    enabled: true,
    editable: 'Tracy Senger',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 31,
    name: 'Darrel Bogisich',
    city: 'Denver',
    age: 55,
    system: 'Windows',
    format: 'Zip',
    lang: 'es',
    firstName: 'Marek',
    lastName: 'Testinson',
    phone: '571345127',
    color: 'blue',
    last_activity: '2024-10-21T00:52:22+02:00',
    active: false,
    country: 'us',
    address: '313 Schmidt Coves',
    status: 'active',
    enabled: false,
    editable: 'Casey Bergnaum-Schamberger',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 32,
    name: 'Lorraine Ortiz',
    city: 'Paris',
    age: 47,
    system: 'Windows',
    format: 'png',
    lang: 'es',
    firstName: 'Marek',
    lastName: 'Kowalczyk',
    phone: '678990320',
    color: 'red',
    last_activity: '2025-01-14T02:31:22+01:00',
    active: false,
    country: 'de',
    address: '581 N Broad Street',
    status: 'inactive',
    enabled: true,
    editable: 'Mildred Okuneva',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 33,
    name: 'Lee Moen Jr.',
    city: 'Paris',
    age: 39,
    system: 'OSX',
    format: 'Zip',
    lang: 'pl',
    firstName: 'Stefan',
    lastName: 'Testovi',
    phone: '666245912',
    color: 'orange',
    last_activity: '2024-12-17T16:19:30+01:00',
    active: false,
    country: 'us',
    address: '49428 Meadow Drive',
    status: 'active',
    enabled: false,
    editable: 'Susie Abshire',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 34,
    name: 'Byron Abshire',
    city: 'New York',
    age: 44,
    system: 'Windows',
    format: 'JPG',
    lang: 'pl',
    firstName: 'Wojtek',
    lastName: 'Testovi',
    phone: '666245912',
    color: 'yellow',
    last_activity: '2024-10-23T14:45:23+02:00',
    active: false,
    country: 'us',
    address: '12407 Fidel Mountains',
    status: 'blocked',
    enabled: true,
    editable: 'Dr. Kate Feeney',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 35,
    name: 'Willis Grimes',
    city: 'New York',
    age: 14,
    system: 'Linux',
    format: 'png',
    lang: 'es',
    firstName: 'Michelle',
    lastName: 'Testovich',
    phone: '588991567',
    color: 'violet',
    last_activity: '2024-10-14T10:17:46+02:00',
    active: true,
    country: 'us',
    address: '605 Williamson Unions',
    status: 'blocked',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 36,
    name: 'Dr. Allen Jacobson DDS',
    city: 'Warsaw',
    age: 33,
    system: 'Linux',
    format: 'Zip',
    lang: 'es',
    firstName: 'Michelle',
    lastName: 'Testovich',
    phone: '571345127',
    color: 'cyan',
    last_activity: '2024-12-08T18:27:31+01:00',
    active: true,
    country: 'it',
    address: '63620 Magdalena Causeway',
    status: 'active',
    enabled: true,
    editable: 'Reginald Bruen',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 37,
    name: 'Kelly Fritsch',
    city: 'New York',
    age: 53,
    system: 'Windows',
    format: 'png',
    lang: 'es',
    firstName: 'Wiktoria',
    lastName: 'Kowalczyk',
    phone: '588991567',
    color: 'cyan',
    last_activity: '2024-10-30T10:16:55+01:00',
    active: true,
    country: 'es',
    address: '97662 Lake Road',
    status: 'inactive',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 38,
    name: 'Mack Daniel',
    city: 'Paris',
    age: 12,
    system: 'Windows',
    format: 'png',
    lang: 'es',
    firstName: 'Martyna',
    lastName: 'Kowalczyk',
    phone: '588991567',
    color: 'cyan',
    last_activity: '2025-01-08T01:50:02+01:00',
    active: true,
    country: 'ru',
    address: '413 Boyer Brooks',
    status: 'active',
    enabled: false,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 39,
    name: 'Omar Klocko',
    city: 'Berlin',
    age: 43,
    system: 'Linux',
    format: 'Zip',
    lang: 'es',
    firstName: 'Martyna',
    lastName: 'Testinson',
    phone: '654666871',
    color: 'cyan',
    last_activity: '2024-11-22T04:01:33+01:00',
    active: false,
    country: 'us',
    address: '64706 Highfield Road',
    status: 'inactive',
    enabled: true,
    editable: 'Dr. Keith Crist',
    checked: true,
    relations: RELATIONS,
    unavailable: true,
    disabled: false,
  },
  {
    key: 40,
    name: 'Carol Zboncak',
    city: 'Berlin',
    age: 36,
    system: 'Windows',
    format: 'Zip',
    lang: 'es',
    firstName: 'Marek',
    lastName: 'Kowalczyk',
    phone: '571345127',
    color: 'yellow',
    last_activity: '2025-01-21T07:46:05+01:00',
    active: true,
    country: 'es',
    address: '119 Joyce Pike',
    status: 'active',
    enabled: false,
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 41,
    name: 'Larry Morar',
    city: 'Denver',
    age: 36,
    system: 'Windows',
    format: 'png',
    lang: 'en',
    firstName: 'John',
    lastName: 'Testinson',
    phone: '678990320',
    color: 'orange',
    last_activity: '2024-11-13T08:16:31+01:00',
    active: false,
    country: 'it',
    address: '57185 Paxton Locks',
    status: 'inactive',
    enabled: false,
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 42,
    name: 'Erma Simonis',
    city: 'Paris',
    age: 14,
    system: 'Linux',
    format: 'png',
    lang: 'es',
    firstName: 'Michelle',
    lastName: 'Doe',
    phone: '654666871',
    color: 'cyan',
    last_activity: '2024-11-25T01:27:51+01:00',
    active: false,
    country: 'pl',
    address: '7359 Johns Oval',
    status: 'active',
    enabled: true,
    editable: 'Bethany Dare MD',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 43,
    name: 'Ralph Collins',
    city: 'New York',
    age: 18,
    system: 'Linux',
    format: 'png',
    lang: 'pl',
    firstName: 'Wojtek',
    lastName: 'Doe',
    phone: '654666871',
    color: 'cyan',
    last_activity: '2025-02-03T18:43:45+01:00',
    active: true,
    country: 'us',
    address: '281 Hansen Ford',
    status: 'inactive',
    enabled: true,
    editable: 'Johnnie Botsford-Pagac III',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 44,
    name: 'Grace Boehm Sr.',
    city: 'Denver',
    age: 44,
    system: 'Linux',
    format: 'Zip',
    lang: 'es',
    firstName: 'Martyna',
    lastName: 'Testovich',
    phone: '571345127',
    color: 'violet',
    last_activity: '2025-01-16T08:53:30+01:00',
    active: false,
    country: 'it',
    address: '11138 Krystel Trafficway',
    status: 'blocked',
    enabled: true,
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 45,
    name: 'Rachael Glover',
    city: 'Warsaw',
    age: 28,
    system: 'Linux',
    format: 'JPG',
    lang: 'es',
    firstName: 'Wojtek',
    lastName: 'Doe',
    phone: '678990320',
    color: 'orange',
    last_activity: '2024-12-17T18:15:33+01:00',
    active: false,
    country: 'es',
    address: '7920 Aditya Drives',
    status: 'active',
    enabled: false,
    editable: 'Lela Waelchi I',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 46,
    name: 'Mr. Joseph Leuschke',
    city: 'Paris',
    age: 42,
    system: 'OSX',
    format: 'png',
    lang: 'en',
    firstName: 'John',
    lastName: 'Testovich',
    phone: '678990320',
    color: 'red',
    last_activity: '2024-10-17T02:49:36+02:00',
    active: true,
    country: 'us',
    address: '6721 Tyreek Dam',
    status: 'blocked',
    enabled: false,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 47,
    name: 'Rodney Hegmann',
    city: 'Paris',
    age: 54,
    system: 'Linux',
    format: 'png',
    lang: 'es',
    firstName: 'Anita',
    lastName: 'Kowalczyk',
    phone: '678990320',
    color: 'purple',
    last_activity: '2024-10-21T06:24:07+02:00',
    active: false,
    country: 'us',
    address: '214 Alene Oval',
    status: 'active',
    enabled: false,
    editable: 'John Yost',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 48,
    name: 'Mattie Sauer II',
    city: 'Denver',
    age: 10,
    system: 'OSX',
    format: 'png',
    lang: 'en',
    firstName: 'Marek',
    lastName: 'Testovich',
    phone: '631001372',
    color: 'yellow',
    last_activity: '2025-01-28T02:02:06+01:00',
    active: true,
    country: 'ru',
    address: '87813 Hamill Crossroad',
    status: 'active',
    enabled: true,
    editable: 'Julius Rice-Bashirian',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 49,
    name: 'Dana Jenkins',
    city: 'Paris',
    age: 52,
    system: 'Linux',
    format: 'JPG',
    lang: 'en',
    firstName: 'Wiktoria',
    lastName: 'Testovi',
    phone: '666245912',
    color: 'red',
    last_activity: '2024-10-25T20:10:12+02:00',
    active: true,
    country: 'de',
    address: '5906 Meadow View',
    status: 'active',
    enabled: false,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 50,
    name: 'Mr. Randolph Robel',
    city: 'Berlin',
    age: 14,
    system: 'Windows',
    format: 'png',
    lang: 'es',
    firstName: 'Stefan',
    lastName: 'Testinson',
    phone: '666245912',
    color: 'orange',
    last_activity: '2024-11-28T16:55:56+01:00',
    active: true,
    country: 'us',
    address: '636 Pat Circles',
    status: 'blocked',
    enabled: true,
    editable: 'Kellie Cummings',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
  {
    key: 51,
    name: 'Dr. Kelli Marquardt Sr.',
    city: 'New York',
    age: 19,
    system: 'Windows',
    format: 'JPG',
    lang: 'en',
    firstName: 'John',
    lastName: 'Testovi',
    phone: '678990320',
    color: 'cyan',
    last_activity: '2024-11-30T01:04:08+01:00',
    active: false,
    country: 'de',
    address: '4541 Schimmel Lakes',
    status: 'blocked',
    enabled: false,
    editable: 'Thelma Torphy',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 52,
    name: 'Katrina Nader',
    city: 'Berlin',
    age: 45,
    system: 'Linux',
    format: 'Zip',
    lang: 'en',
    firstName: 'Wojtek',
    lastName: 'Testovi',
    phone: '588991567',
    color: 'red',
    last_activity: '2024-11-28T05:35:04+01:00',
    active: false,
    country: 'ru',
    address: '58404 Prospect Street',
    status: 'blocked',
    enabled: false,
    editable: 'Melba Rohan DVM',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 53,
    name: 'Dr. Wilson Wisoky',
    city: 'New York',
    age: 21,
    system: 'Linux',
    format: 'png',
    lang: 'es',
    firstName: 'Wojtek',
    lastName: 'Testinson',
    phone: '654666871',
    color: 'violet',
    last_activity: '2024-11-30T18:06:11+01:00',
    active: true,
    country: 'es',
    address: '92204 Beier Ways',
    status: 'blocked',
    enabled: true,
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 54,
    name: 'Henry Gorczany',
    city: 'Paris',
    age: 26,
    system: 'Linux',
    format: 'png',
    lang: 'pl',
    firstName: 'John',
    lastName: 'Testovi',
    phone: '571345127',
    color: 'yellow',
    last_activity: '2024-12-18T18:17:59+01:00',
    active: false,
    country: 'de',
    address: '70466 Travon Overpass',
    status: 'blocked',
    enabled: true,
    editable: 'Cynthia Boehm',
    checked: false,
    relations: RELATIONS,
    unavailable: false,
    disabled: false,
  },
  {
    key: 55,
    name: 'Sheryl Stehr',
    city: 'Warsaw',
    age: 41,
    system: 'Windows',
    format: 'JPG',
    lang: 'pl',
    firstName: 'John',
    lastName: 'Kowalczyk',
    phone: '654666871',
    color: 'yellow',
    last_activity: '2025-01-17T15:56:03+01:00',
    active: true,
    country: 'es',
    address: '34116 Lew Valleys',
    status: 'inactive',
    enabled: false,
    editable: 'Grady Turcotte',
    checked: true,
    relations: RELATIONS,
    unavailable: false,
    disabled: true,
  },
];

export type RowType = typeof DATA_SOURCE[number];
export type ColumnType = DSColumnType<RowType> & AdditionalColumnData;

export const COLUMNS: ColumnType[] = [
  {
    title: 'Name',
    dataIndex: 'name',
    width: 254,
    fixed: 'left',
    key: 'name',
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.name.localeCompare(b.name),
      multiple: 1,
    },
    className: 'chromatic-ignore',
    sortRender: 'string',
    defaultSortOrder: 'ascend',
  },
  {
    title: 'City',
    dataIndex: 'city',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'city',
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.city.localeCompare(b.city),
      multiple: 2,
    },
    className: 'chromatic-ignore',
    sortRender: 'string',
  },
  {
    title: 'System',
    dataIndex: 'system',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'system',
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.system.localeCompare(b.system),
      multiple: 3,
    },
    className: 'chromatic-ignore',
    sortRender: 'string',
  },
  {
    title: 'Format',
    dataIndex: 'format',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    key: 'format',
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.system.localeCompare(b.system),
      multiple: 4,
    },
    className: 'chromatic-ignore',
    sortRender: 'string',
  },
  {
    title: 'Age',
    dataIndex: 'age',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    fixed: 'right',
    key: 'age',
    icon: { component: <VarTypeNumberM /> },
    iconTooltip: { component: <InfoFillS /> },
    sorter: {
      compare: (a, b) => a.age - b.age,
      multiple: 5,
    },
    className: 'chromatic-ignore',
  },
];

export const COLUMNS_WITH_FIXED_ACTION: ColumnType[] = [
  {
    title: 'Name',
    dataIndex: 'avatar',
    key: 'avatar-m',
    width: 254,
    textWrap: 'word-break',
    ellipsis: true,
    icon: { component: <VarTypeListM /> },
    iconTooltip: { component: <InfoFillS /> },
    className: 'chromatic-ignore',
    render: (_avatar, record) => {
      const user = true
        ? {
          tooltip: true,
          firstName: record.name,
          lastName: record.lastName,
          email: `${record.name}.${record.lastName}@synerise.com`,
          avatar: AVATAR_IMAGE,
        }
        : {};
      return (
        <TableCell.AvatarLabelCell
          avatarAction={action('Avatar Action')}
          avatar={<UserAvatar user={user} badgeStatus="active" size="medium" backgroundColor={record.color} />}
          title={`${record.name} ${record.lastName}`}
        />
      );
    },
  },
  {
    title: 'Email address',
    width: 254,
    ellipsis: true,
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    className: 'chromatic-ignore',
    render: record => <>{`${record.name}.${record.lastName}@synerise.com`}</>,
  },
  {
    title: 'Phone',
    dataIndex: 'phone',
    key: 'phone',
    width: 180,
    textWrap: 'word-break',
    ellipsis: true,
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sortRender: 'string',
    className: 'chromatic-ignore',
  },
  {
    title: 'City',
    dataIndex: 'city',
    key: 'city',
    ellipsis: true,
    width: 120,
    icon: { component: <VarTypeStringM /> },
    iconTooltip: { component: <InfoFillS /> },
    sortRender: 'string',
    className: 'chromatic-ignore',
  },
  {
    title: 'Age',
    key: 'age',
    dataIndex: 'age',
    width: 100,
    icon: { component: <VarTypeNumberM /> },
    iconTooltip: { component: <InfoFillS /> },
    className: 'chromatic-ignore',
  },
  {
    title: 'Last activity',
    key: 'last_activity',
    dataIndex: 'last_activity',
    width: 254,
    icon: { component: <VarTypeDateM /> },
    iconTooltip: { component: <InfoFillS /> },
    className: 'chromatic-ignore',
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
    textWrap: 'word-break',
    width: 100,
    ellipsis: true,
    icon: { component: <VarTypeBooleanM /> },
    tooltip: { title: 'Tooltip', description: 'Description' },
    className: 'chromatic-ignore',
    render: status => <TableCell.StatusLabelCell status={status} label={status} />,
  },
  {
    title: (
      <Button type="ghost" mode="single-icon">
        <Icon component={<SettingsM />} />
      </Button>
    ),
    dataIndex: 'skeleton',
    key: 'skeleton-desc',
    width: 50,
    textWrap: 'word-break',
    ellipsis: true,
    fixed: 'right',
    icon: { component: <VarTypeListM /> },
    iconTooltip: { component: <InfoFillS /> },
    className: 'chromatic-ignore',
    render: button => {
      return (
        <Dropdown
          overlay={
            <Dropdown.Wrapper
              style={{ width: '220px' }}
              onKeyDown={event => focusWithArrowKeys(event, 'ds-menu-item', () => { })}
            >
              <Menu dataSource={menuData} asDropdownMenu={true} style={{ width: '100%' }} />
            </Dropdown.Wrapper>
          }
        >
          <Button type="ghost" mode="single-icon">
            <Icon component={<OptionHorizontalM />} />
          </Button>
        </Dropdown>
      );
    },
  },
];
