export const SEARCH_BAR_PADDING_LEFT = 16;
export const SEARCH_BAR_PADDING_RIGHT = 12;

export const ICON_LEFT_SIZE = 24;
export const ICON_LEFT_MARGIN_RIGHT = 12;

export const CLEAR_ICON_SIZE = 18;
export const CLEAR_ICON_MARGIN_LEFT = 12;

export const VALUE_PREFIX_WRAPPER_LEFT_VALUE =
  SEARCH_BAR_PADDING_LEFT + ICON_LEFT_SIZE + ICON_LEFT_MARGIN_RIGHT;
export const VALUE_PREFIX_WRAPPER_RIGHT_MARGIN = 4;
