import { DSColumnType } from '@synerise/ds-table';

import { AdditionalColumnData } from '../Table.types';

export const DATA_SOURCE = [
  {
    id: '0',
    name: 'Sylvester Glover',
    company: 'Lind Inc',
    transactionValue: 864.55,
    transactionType: 'invoice',
  },
  {
    id: '1',
    name: 'Dr. Deborah Conroy',
    company: 'Heidenreich Inc',
    transactionValue: 646.14,
    transactionType: 'deposit',
  },
  {
    id: '2',
    name: 'Muriel Heidenreich',
    company: 'Zemlak, Sporer and Kassulke',
    transactionValue: 74.5,
    transactionType: 'withdrawal',
  },
  {
    id: '3',
    name: 'Calvin Lockman',
    company: 'Nikolaus, Schroeder and Connelly',
    transactionValue: 841.83,
    transactionType: 'invoice',
  },
  {
    id: '4',
    name: 'Angel Swift',
    company: 'Sauer, Weissnat and Glover',
    transactionValue: 167.87,
    transactionType: 'invoice',
  },
  {
    id: '5',
    name: 'Leslie Kuphal',
    company: 'Krajcik, Schowalter and Treutel',
    transactionValue: 423.83,
    transactionType: 'payment',
  },
  {
    id: '6',
    name: 'Scott Hirthe PhD',
    company: 'Heidenreich Inc',
    transactionValue: 654.13,
    transactionType: 'payment',
  },
  {
    id: '7',
    name: 'Mr. Pedro Morar',
    company: 'McKenzie - Wunsch',
    transactionValue: 125.34,
    transactionType: 'invoice',
  },
  {
    id: '8',
    name: 'Alexandra Simonis',
    company: 'McKenzie - Wunsch',
    transactionValue: 674.88,
    transactionType: 'payment',
  },
  {
    id: '9',
    name: 'Rita Okuneva',
    company: 'Osinski - Roberts',
    transactionValue: 780.48,
    transactionType: 'payment',
  },
  {
    id: '10',
    name: 'Tommy Bode',
    company: 'Nikolaus, Schroeder and Connelly',
    transactionValue: 591.86,
    transactionType: 'deposit',
  },
  {
    id: '11',
    name: 'Bobbie Watsica',
    company: 'Zemlak, Sporer and Kassulke',
    transactionValue: 205.96,
    transactionType: 'payment',
  },
  {
    id: '12',
    name: 'Miss Olivia Balistreri',
    company: 'Schumm, Stehr and Wisozk',
    transactionValue: 906.11,
    transactionType: 'withdrawal',
  },
  {
    id: '13',
    name: 'Dorothy Larkin',
    company: 'Zemlak, Sporer and Kassulke',
    transactionValue: 126.24,
    transactionType: 'payment',
  },
  {
    id: '14',
    name: 'Wade Bednar',
    company: 'Sauer, Weissnat and Glover',
    transactionValue: 713.12,
    transactionType: 'withdrawal',
  },
  {
    id: '15',
    name: 'Janice Mayert',
    company: 'Osinski - Roberts',
    transactionValue: 575.95,
    transactionType: 'deposit',
  },
  {
    id: '16',
    name: 'Bethany Skiles',
    company: 'Osinski - Roberts',
    transactionValue: 492.4,
    transactionType: 'invoice',
  },
  {
    id: '17',
    name: 'Marlon Kiehn',
    company: 'Lind Inc',
    transactionValue: 532.23,
    transactionType: 'withdrawal',
  },
  {
    id: '18',
    name: 'Grace Rau',
    company: 'Sauer, Weissnat and Glover',
    transactionValue: 465.05,
    transactionType: 'deposit',
  },
  {
    id: '19',
    name: 'Stewart Kirlin',
    company: 'Sauer, Weissnat and Glover',
    transactionValue: 772.73,
    transactionType: 'deposit',
  },
  {
    id: '20',
    name: 'Miranda Cassin',
    company: 'McKenzie - Wunsch',
    transactionValue: 431.72,
    transactionType: 'withdrawal',
  },
  {
    id: '21',
    name: 'Simon Bernhard-Reichert',
    company: 'Osinski - Roberts',
    transactionValue: 905.37,
    transactionType: 'invoice',
  },
  {
    id: '22',
    name: 'Jennifer Sipes',
    company: 'Osinski - Roberts',
    transactionValue: 25.28,
    transactionType: 'payment',
  },
  {
    id: '23',
    name: 'Dianne Johnson',
    company: 'McKenzie - Wunsch',
    transactionValue: 118.89,
    transactionType: 'invoice',
  },
  {
    id: '24',
    name: 'Rosa Kunde',
    company: 'Sauer, Weissnat and Glover',
    transactionValue: 966.44,
    transactionType: 'invoice',
  },
  {
    id: '25',
    name: 'Dianne Schinner',
    company: 'Lind Inc',
    transactionValue: 106.4,
    transactionType: 'deposit',
  },
  {
    id: '26',
    name: 'Lloyd Waters',
    company: 'Osinski - Roberts',
    transactionValue: 395.54,
    transactionType: 'deposit',
  },
  {
    id: '27',
    name: 'Mr. Julian Bode PhD',
    company: 'Kirlin - Murray',
    transactionValue: 587.92,
    transactionType: 'payment',
  },
  {
    id: '28',
    name: 'Geoffrey Upton',
    company: 'Sauer, Weissnat and Glover',
    transactionValue: 195.1,
    transactionType: 'payment',
  },
  {
    id: '29',
    name: 'Dr. Amos Balistreri',
    company: 'Kirlin - Murray',
    transactionValue: 62.98,
    transactionType: 'deposit',
  },
  {
    id: '30',
    name: 'Miss Tricia Champlin',
    company: 'Osinski - Roberts',
    transactionValue: 400.13,
    transactionType: 'deposit',
  },
  {
    id: '31',
    name: 'Lorraine Cruickshank',
    company: 'Nikolaus, Schroeder and Connelly',
    transactionValue: 548.74,
    transactionType: 'withdrawal',
  },
  {
    id: '32',
    name: 'Priscilla Cruickshank',
    company: 'Osinski - Roberts',
    transactionValue: 209.06,
    transactionType: 'payment',
  },
  {
    id: '33',
    name: 'Juana Abbott',
    company: 'Zemlak, Sporer and Kassulke',
    transactionValue: 24.84,
    transactionType: 'invoice',
  },
  {
    id: '34',
    name: 'Joyce Dickens',
    company: 'Nikolaus, Schroeder and Connelly',
    transactionValue: 810.9,
    transactionType: 'withdrawal',
  },
  {
    id: '35',
    name: 'Roland Mayer',
    company: 'Kirlin - Murray',
    transactionValue: 548.05,
    transactionType: 'payment',
  },
  {
    id: '36',
    name: 'Clara Goldner',
    company: 'Osinski - Roberts',
    transactionValue: 649.03,
    transactionType: 'withdrawal',
  },
  {
    id: '37',
    name: 'Salvador Leannon',
    company: 'Krajcik, Schowalter and Treutel',
    transactionValue: 997.71,
    transactionType: 'deposit',
  },
  {
    id: '38',
    name: 'Cecil VonRueden-Treutel',
    company: 'Lind Inc',
    transactionValue: 402.55,
    transactionType: 'deposit',
  },
  {
    id: '39',
    name: 'Jorge Schoen',
    company: 'Krajcik, Schowalter and Treutel',
    transactionValue: 696.93,
    transactionType: 'withdrawal',
  },
  {
    id: '40',
    name: 'Tom Beer-Doyle I',
    company: 'Schumm, Stehr and Wisozk',
    transactionValue: 326.33,
    transactionType: 'deposit',
  },
  {
    id: '41',
    name: 'Blanca Abbott',
    company: 'Kirlin - Murray',
    transactionValue: 706.41,
    transactionType: 'invoice',
  },
  {
    id: '42',
    name: 'Johnnie Wisozk',
    company: 'Heidenreich Inc',
    transactionValue: 327.32,
    transactionType: 'payment',
  },
  {
    id: '43',
    name: 'Lauren Franecki',
    company: 'Schumm, Stehr and Wisozk',
    transactionValue: 962.53,
    transactionType: 'withdrawal',
  },
  {
    id: '44',
    name: 'Claude Nikolaus',
    company: 'Kirlin - Murray',
    transactionValue: 499.1,
    transactionType: 'payment',
  },
  {
    id: '45',
    name: 'Todd Cummings',
    company: 'Osinski - Roberts',
    transactionValue: 423.44,
    transactionType: 'invoice',
  },
  {
    id: '46',
    name: 'Beverly Volkman',
    company: 'Schumm, Stehr and Wisozk',
    transactionValue: 403.84,
    transactionType: 'withdrawal',
  },
  {
    id: '47',
    name: 'Theodore Collins',
    company: 'Sauer, Weissnat and Glover',
    transactionValue: 988.87,
    transactionType: 'payment',
  },
  {
    id: '48',
    name: 'Bernadette DuBuque',
    company: 'Schumm, Stehr and Wisozk',
    transactionValue: 120.95,
    transactionType: 'invoice',
  },
  {
    id: '49',
    name: 'Barry Donnelly',
    company: 'Zemlak, Sporer and Kassulke',
    transactionValue: 416.15,
    transactionType: 'deposit',
  },
];

export type RowType = typeof DATA_SOURCE[number];
export type ColumnType = DSColumnType<RowType> & AdditionalColumnData;

export const sortRenderTypes: ['string', 'default'] = ['string', 'default'];

export const COLUMNS: ColumnType[] = [
  {
    key: 'name',
    title: 'Name',
    dataIndex: 'name',
    sorter: {
      compare: (a, b) => a.name.localeCompare(b.name),
      multiple: 1,
    },
    sortRender: 'string',
    defaultSortOrder: 'ascend',
  },
  {
    key: 'company',
    title: 'Company',
    dataIndex: 'company',
    sorter: {
      compare: (a, b) => a.company.localeCompare(b.company),
      multiple: 2,
    },
    sortRender: 'string',
  },
  {
    key: 'transactionValue',
    title: 'Transaction value',
    dataIndex: 'transactionValue',
    sorter: {
      compare: (a, b) => a.transactionValue - b.transactionValue,
      multiple: 3,
    },
    sortRender: 'string',
  },
  {
    key: 'transactionType',
    title: 'Transaction type',
    dataIndex: 'transactionType',
    sorter: {
      compare: (a, b) => a.transactionType.localeCompare(b.transactionType),
      multiple: 4,
    },
    sortRender: 'string',
  },
];
