import type { ReactNode } from 'react';
import type { IntlShape } from 'react-intl';
import type { SearchBarProps } from '@synerise/ds-search-bar/dist/SearchBar.types';
import type { DropdownProps } from '@synerise/ds-dropdown';
import type { InformationCardTooltipProps } from '@synerise/ds-information-card';
import type { ListItemProps } from '@synerise/ds-list-item';
import type { ScrollbarAdditionalProps } from '@synerise/ds-scrollbar';

export type ItemPickerSize = 'small' | 'large';

export type ItemPickerProps = {
  dataSource: ListItemProps[];
  intl: IntlShape;
  onChange: (item: ListItemProps) => void;
  onClear?: () => void;
  placeholder: ReactNode;
  changeButtonLabel?: ReactNode;
  clear?: ReactNode;
  clearConfirmTitle?: string;
  closeOnBottomAction?: boolean;
  description?: ReactNode;
  disabled?: boolean;
  dropdownBottomAction?: ReactNode;
  dropdownProps?: Partial<DropdownProps>;
  dropdownRowHeight?: number;
  dropdownVisibleRows?: number;
  error?: boolean;
  errorMessage?: ReactNode;
  label?: ReactNode;
  onBlur?: () => void;
  onFocus?: () => void;
  noResults?: string;
  noText?: string;
  placeholderIcon?: ReactNode;
  searchPlaceholder?: string;
  searchBarProps?: Partial<SearchBarProps>;
  hideSearchBar?: boolean;
  selectedItem?: ListItemProps | undefined;
  size?: ItemPickerSize;
  tooltip?: ReactNode;
  informationCardTooltipProps?: Omit<InformationCardTooltipProps, 'children'>;
  withClearConfirmation?: boolean;
  yesText?: string;
  scrollbarProps?: ScrollbarAdditionalProps;
};
